// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

export function Abort(request: domain$0.ThreadRequest): $CancellablePromise<domain$0.CommandResult> {
    return $Call.ByID(3108823947, request);
}

export function AbortBash(request: domain$0.ThreadRequest): $CancellablePromise<domain$0.CommandResult> {
    return $Call.ByID(3178304269, request);
}

export function AbortRetry(request: domain$0.ThreadRequest): $CancellablePromise<domain$0.CommandResult> {
    return $Call.ByID(1593570851, request);
}

export function Bash(request: domain$0.BashRequest): $CancellablePromise<domain$0.CommandResult> {
    return $Call.ByID(4198354505, request);
}

export function CloneSession(request: domain$0.ThreadRequest): $CancellablePromise<domain$0.CommandResult> {
    return $Call.ByID(1682910576, request);
}

export function Compact(request: domain$0.CompactRequest): $CancellablePromise<domain$0.CommandResult> {
    return $Call.ByID(3349501200, request);
}

export function DeleteSessionMessage(request: domain$0.SessionMessageRequest): $CancellablePromise<domain$0.CommandResult> {
    return $Call.ByID(2191535415, request);
}

export function EditSessionMessage(request: domain$0.SessionMessageRequest): $CancellablePromise<domain$0.CommandResult> {
    return $Call.ByID(1154625060, request);
}

export function ExcludeSessionMessageFromContext(request: domain$0.SessionMessageRequest): $CancellablePromise<domain$0.CommandResult> {
    return $Call.ByID(130865583, request);
}

export function ExportSession(request: domain$0.ExportSessionRequest): $CancellablePromise<domain$0.CommandResult> {
    return $Call.ByID(1940287575, request);
}

export function ForkSession(request: domain$0.SessionForkRequest): $CancellablePromise<domain$0.CommandResult> {
    return $Call.ByID(945819957, request);
}

export function ForkSessionAt(request: domain$0.SessionMessageRequest): $CancellablePromise<domain$0.CommandResult> {
    return $Call.ByID(2392909880, request);
}

export function GetAvailableModels(request: domain$0.ThreadRequest): $CancellablePromise<domain$0.CommandResult> {
    return $Call.ByID(1063668030, request);
}

export function GetAvailableThinkingLevels(request: domain$0.ThreadRequest): $CancellablePromise<domain$0.CommandResult> {
    return $Call.ByID(1164900579, request);
}

export function GetCommands(request: domain$0.ThreadRequest): $CancellablePromise<domain$0.CommandResult> {
    return $Call.ByID(3857513703, request);
}

export function GetDiagnostics(request: domain$0.ThreadRequest): $CancellablePromise<string> {
    return $Call.ByID(3815408115, request);
}

export function GetForkMessages(request: domain$0.ThreadRequest): $CancellablePromise<domain$0.CommandResult> {
    return $Call.ByID(4014146621, request);
}

export function GetMessages(request: domain$0.ThreadRequest): $CancellablePromise<domain$0.CommandResult> {
    return $Call.ByID(4124291153, request);
}

export function GetSessionBranches(request: domain$0.ThreadRequest): $CancellablePromise<domain$0.SessionBranches> {
    return $Call.ByID(3628737643, request);
}

export function GetSessionStats(request: domain$0.ThreadRequest): $CancellablePromise<domain$0.CommandResult> {
    return $Call.ByID(3933842142, request);
}

export function GetState(request: domain$0.ThreadRequest): $CancellablePromise<domain$0.CommandResult> {
    return $Call.ByID(221571890, request);
}

export function ReplaySessionMessage(request: domain$0.SessionMessageRequest): $CancellablePromise<domain$0.CommandResult> {
    return $Call.ByID(2965284235, request);
}

export function RespondExtensionUI(request: domain$0.ExtensionUIResponseRequest): $CancellablePromise<void> {
    return $Call.ByID(3284289759, request);
}

export function SendPrompt(request: domain$0.PromptRequest): $CancellablePromise<domain$0.CommandResult> {
    return $Call.ByID(3002925231, request);
}

export function SetAutoCompaction(request: domain$0.ToggleRequest): $CancellablePromise<domain$0.CommandResult> {
    return $Call.ByID(1633786311, request);
}

export function SetAutoRetry(request: domain$0.ToggleRequest): $CancellablePromise<domain$0.CommandResult> {
    return $Call.ByID(1349105172, request);
}

export function SetFollowUpMode(request: domain$0.QueueModeRequest): $CancellablePromise<domain$0.CommandResult> {
    return $Call.ByID(2936718514, request);
}

export function SetModel(request: domain$0.ModelRequest): $CancellablePromise<domain$0.CommandResult> {
    return $Call.ByID(1973285154, request);
}

export function SetSessionName(request: domain$0.SessionNameRequest): $CancellablePromise<domain$0.CommandResult> {
    return $Call.ByID(2628890940, request);
}

export function SetSteeringMode(request: domain$0.QueueModeRequest): $CancellablePromise<domain$0.CommandResult> {
    return $Call.ByID(168576489, request);
}

export function SetThinkingLevel(request: domain$0.ThinkingRequest): $CancellablePromise<domain$0.CommandResult> {
    return $Call.ByID(4170421181, request);
}

export function StartSession(request: domain$0.StartSessionRequest): $CancellablePromise<domain$0.LiveSession> {
    return $Call.ByID(2109278255, request);
}

export function StopSession(request: domain$0.ThreadRequest): $CancellablePromise<void> {
    return $Call.ByID(4066002425, request);
}
