// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * The host owns page identity. Unmounting a BrowserPane only hides its viewport.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

export function CloseTab(id: string): $CancellablePromise<void> {
    return $Call.ByID(3653653757, id);
}

export function Command(id: string, command: string): $CancellablePromise<void> {
    return $Call.ByID(1718251299, id, command);
}

export function KeepTab(id: string): $CancellablePromise<void> {
    return $Call.ByID(3001718334, id);
}

export function OpenURL(request: domain$0.BrowserOpenURLRequest): $CancellablePromise<domain$0.BrowserStatus> {
    return $Call.ByID(3772911123, request);
}

export function SetBounds(request: domain$0.BrowserBoundsRequest): $CancellablePromise<void> {
    return $Call.ByID(2452683139, request);
}

export function StartTab(request: domain$0.BrowserStartRequest): $CancellablePromise<domain$0.BrowserStatus> {
    return $Call.ByID(1338707273, request);
}
