// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

export function AddWorkspace(request: domain$0.AddWorkspaceRequest): $CancellablePromise<domain$0.WorkspaceSummary> {
    return $Call.ByID(1066149365, request);
}

export function DeleteSession(request: domain$0.DeleteSessionRequest): $CancellablePromise<domain$0.DeletedSession> {
    return $Call.ByID(3884599674, request);
}

export function DeleteWorkspaceSessions(request: domain$0.WorkspaceRequest): $CancellablePromise<void> {
    return $Call.ByID(982674982, request);
}

export function GetDesktopState(): $CancellablePromise<domain$0.DesktopState> {
    return $Call.ByID(3825154050);
}

export function GetSessionSnapshot(request: domain$0.SessionSnapshotRequest): $CancellablePromise<domain$0.SessionSnapshot> {
    return $Call.ByID(1538082309, request);
}

export function GetSessionUsage(request: domain$0.ListSessionsRequest): $CancellablePromise<domain$0.SessionUsageSummary> {
    return $Call.ByID(3606949216, request);
}

export function ListSessions(request: domain$0.ListSessionsRequest): $CancellablePromise<domain$0.SessionSummary[] | null> {
    return $Call.ByID(4007152500, request);
}

export function ListWorkspaceApplications(): $CancellablePromise<domain$0.WorkspaceApplication[] | null> {
    return $Call.ByID(2105555461);
}

export function ListWorkspaces(): $CancellablePromise<domain$0.WorkspaceSummary[] | null> {
    return $Call.ByID(3370722199);
}

export function OpenWorkspace(request: domain$0.WorkspaceRequest): $CancellablePromise<void> {
    return $Call.ByID(13033406, request);
}

export function OpenWorkspaceWith(request: domain$0.OpenWorkspaceWithRequest): $CancellablePromise<void> {
    return $Call.ByID(3899889722, request);
}

export function PickWorkspace(request: domain$0.PickWorkspaceRequest): $CancellablePromise<string> {
    return $Call.ByID(2864021601, request);
}

export function RemoveWorkspace(request: domain$0.WorkspaceRequest): $CancellablePromise<void> {
    return $Call.ByID(1732600386, request);
}

export function RenameWorkspace(request: domain$0.RenameWorkspaceRequest): $CancellablePromise<domain$0.WorkspaceSummary> {
    return $Call.ByID(3678873748, request);
}

export function SaveDesktopState(state: domain$0.DesktopState): $CancellablePromise<void> {
    return $Call.ByID(2642902473, state);
}

/**
 * SessionSnapshotRef mints the reference that lets the webview fetch this transcript from the app's
 * own asset server instead of carrying it across the bridge. An empty string with no error means
 * "this process cannot sign references" - the caller then uses `GetSessionSnapshot`, which is a
 * slower snapshot rather than a broken one.
 */
export function SessionSnapshotRef(request: domain$0.SessionSnapshotRequest): $CancellablePromise<string> {
    return $Call.ByID(2204929740, request);
}
