// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

export function CheckForUpdates(): $CancellablePromise<domain$0.UpdateCheckResult> {
    return $Call.ByID(319967009);
}

/**
 * CheckRuntime performs the potentially slow Pi CLI version check after the
 * initial desktop state has been returned to the frontend.
 */
export function CheckRuntime(): $CancellablePromise<domain$0.PiRuntimeStatus> {
    return $Call.ByID(4290148594);
}

export function GetBootstrapState(): $CancellablePromise<domain$0.BootstrapState> {
    return $Call.ByID(3493914889);
}

/**
 * ReadUserConfig returns the hand-editable streaming config. It creates the file
 * with the defaults the first time, so the path advertised in the settings
 * dialog can actually be opened and edited.
 */
export function ReadUserConfig(): $CancellablePromise<domain$0.UserConfigView> {
    return $Call.ByID(1428877975);
}

export function SaveWindowState(state: domain$0.WindowState): $CancellablePromise<void> {
    return $Call.ByID(2027655592, state);
}

export function ToggleDebugMode(): $CancellablePromise<boolean> {
    return $Call.ByID(887430002);
}

/**
 * WriteUserConfig stores the panel policy in the same file the user edits by
 * hand, which keeps one source of truth: the dialog writes it, and so does a
 * text editor. Unknown keys survive because userconfig keeps them verbatim.
 */
export function WriteUserConfig(view: domain$0.UserConfigView): $CancellablePromise<domain$0.UserConfigView> {
    return $Call.ByID(706529932, view);
}
