// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * AddModels writes a discovered model set in one atomic models.json update.
 * Existing IDs are rejected so the caller cannot silently overwrite manual settings.
 */
export function AddModels(request: domain$0.AddModelsConfigRequest): $CancellablePromise<domain$0.ModelConfigSnapshot> {
    return $Call.ByID(2281211154, request);
}

export function DeleteModel(request: domain$0.DeleteModelConfigRequest): $CancellablePromise<domain$0.ModelConfigSnapshot> {
    return $Call.ByID(4006858259, request);
}

export function DeleteProvider(request: domain$0.DeleteProviderConfigRequest): $CancellablePromise<domain$0.ModelConfigSnapshot> {
    return $Call.ByID(2482877219, request);
}

export function DiscoverModels(request: domain$0.DiscoverModelsRequest): $CancellablePromise<domain$0.ModelDiscoveryResult> {
    return $Call.ByID(3039346508, request);
}

export function GetAccountQuota(request: domain$0.ModelQuotaRequest): $CancellablePromise<domain$0.ModelQuotaResult> {
    return $Call.ByID(4154092574, request);
}

export function GetConfiguredModels(): $CancellablePromise<domain$0.SelectableModel[] | null> {
    return $Call.ByID(2299936945);
}

export function GetModelsConfig(): $CancellablePromise<domain$0.ModelConfigSnapshot> {
    return $Call.ByID(1396541851);
}

/**
 * MissingProviderEnv reports every provider whose API key is an environment reference this process
 * cannot resolve. Pi drops such a provider silently, so the only symptom is
 * `Model not found: bailian/qwen3.8-flash` plus a blank thinking-level list - and a .app started by
 * Finder never reads ~/.zshrc, which is where those variables usually live.
 */
export function MissingProviderEnv(): $CancellablePromise<domain$0.ProviderEnvIssue[] | null> {
    return $Call.ByID(3241379253);
}

export function TestModel(request: domain$0.TestModelConfigRequest): $CancellablePromise<domain$0.ModelTestResult> {
    return $Call.ByID(838171198, request);
}

export function UpsertModel(request: domain$0.UpsertModelConfigRequest): $CancellablePromise<domain$0.ModelConfigSnapshot> {
    return $Call.ByID(4232212211, request);
}
