// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../encoding/json/models.js";

export interface AddModelsConfigRequest {
    "originalProviderId"?: string;
    "providerId": string;
    "baseUrl"?: string;
    "api"?: string;
    "apiKey"?: string;
    "headers"?: { [_ in string]?: string } | null;
    "providerCompatJson"?: string;
    "models": ManagedModel[] | null;
}

export interface AddWorkspaceRequest {
    "path": string;
    "trust": string;
}

export interface BashRequest {
    "threadId": string;
    "command": string;
    "excludeFromContext"?: boolean;
}

export interface BootstrapState {
    "productName": string;
    "appVersion": string;
    "wailsVersion": string;
    "workingDirectory": string;
    "runtime": PiRuntimeStatus;
    "window": WindowState;

    /**
     * ProviderEnvIssues is the startup precheck: providers whose `$VAR` API key never reached this
     * process. A .app opened from Finder does not read ~/.zshrc, so Pi silently drops them.
     */
    "providerEnvIssues"?: ProviderEnvIssue[] | null;
}

export interface BrowserBoundsRequest {
    "tabId": string;
    "x": number;
    "y": number;
    "width": number;
    "height": number;
    "visible": boolean;
}

export interface BrowserOpenURLRequest {
    "tabId"?: string;
    "url": string;
}

export interface BrowserStartRequest {
    "tabId": string;
    "threadId": string;
    "url": string;
}

export interface BrowserStatus {
    "tabId": string;
    "threadId": string;
    "temporary": boolean;
    "loading": boolean;
    "canGoBack": boolean;
    "canGoForward": boolean;
    "error"?: string;
    "attached": boolean;
    "url"?: string;
    "title"?: string;
    "profileDir"?: string;
}

export interface CommandResult {
    "command": string;
    "dataJson"?: string;
}

export interface CompactRequest {
    "threadId": string;
    "customInstructions"?: string;
}

export interface ConnectRemoteTargetRequest {
    "targetId"?: string;
    "name"?: string;
    "hostAlias"?: string;
}

export interface CreateManagedSkillRequest {
    "scope": SkillScope;
    "workspacePath"?: string;
    "name": string;
    "description": string;
}

export interface DecideRemoteRootRequest {
    "token": string;
    "trust": string;
}

export interface DeleteModelConfigRequest {
    "providerId": string;
    "modelId": string;
}

export interface DeleteProviderConfigRequest {
    "providerId": string;
}

export interface DeleteSessionRequest {
    "path": string;
}

export interface DeletedSession {
    "recoveryPath": string;
}

export interface DesktopPreferences {
    "appearance": string;
    "language": string;
    "fontFamily": string;
    "fontSize": number;
    "lightCodeTheme"?: string;
    "darkCodeTheme"?: string;
    "showCodeLineNumbers"?: boolean;
    "wrapCodeLines"?: boolean;
    "codeFontSize"?: number;
    "offlineMode": boolean;
    "proxyEnabled": boolean;
    "proxyUrl"?: string;
    "streamingBehavior": string;
    "sidebarCollapsed": boolean;
    "sidebarWidth"?: number;
    "inspectorOpen": boolean;
    "inspectorWidth"?: number;
    "inspectorTab": string;
    "panelState"?: string;
    "notificationsEnabled": boolean;
    "updateChecksEnabled": boolean;
    "closeToTray": boolean;
    "workspaceApplication"?: string;
}

export interface DesktopState {
    "activeThreadId"?: string;
    "threads": DesktopThreadState[] | null;
    "scheduledTasks"?: ScheduledTaskState[] | null;
    "preferences"?: DesktopPreferences | null;
}

export interface DesktopThreadState {
    "id": string;
    "title": string;
    "workspaceId"?: string;
    "workspacePath": string;
    "trust": string;
    "status": string;
    "sessionPath"?: string;
    "draft"?: string;
    "createdAt"?: string;
    "updatedAt"?: string;
    "unread"?: boolean;
}

export interface DiscoverModelsRequest {
    "baseUrl": string;
    "api": string;
    "apiKey"?: string;
    "headers"?: { [_ in string]?: string } | null;
}

export interface DiscoveredModel {
    "id": string;
    "name"?: string;
    "contextWindow"?: number;
    "maxTokens"?: number;
    "reasoning"?: boolean;
    "imageInput"?: boolean;
}

export interface ExportOrphanSessionRequest {
    "path": string;
    "outputPath": string;
}

export interface ExportSessionRequest {
    "threadId": string;
    "outputPath"?: string;
}

export interface ExtensionUIResponseRequest {
    "threadId": string;
    "requestId": string;
    "value"?: string;
    "confirmed"?: boolean | null;
    "cancelled"?: boolean;
}

export interface GitBranch {
    "name": string;
    "fullName": string;
    "remote"?: boolean;
    "current"?: boolean;
    "upstream"?: string;
    "commit": string;
    "worktreePath"?: string;
}

export interface GitBranchInventory {
    "branches": GitBranch[] | null;
}

export interface GitChangedFile {
    "path": string;
    "originalPath"?: string;
    "indexStatus": string;
    "worktreeStatus": string;
}

export interface GitStatus {
    "isRepository": boolean;
    "branch"?: string;
    "detached"?: boolean;
    "ahead"?: number;
    "behind"?: number;
    "files": GitChangedFile[] | null;
}

export interface ImageContent {
    "type": string;
    "data": string;
    "mimeType": string;
}

export interface ListManagedSkillsRequest {
    "workspacePath"?: string;
}

export interface ListMcpServersRequest {
    "workspacePath"?: string;
}

export interface ListPiPackagesRequest {
    "workspacePath"?: string;
}

export interface ListPromptTemplatesRequest {
    "workspacePath"?: string;
}

export interface ListSessionsRequest {
    "workspacePath"?: string;
}

export interface LiveSession {
    "threadId": string;
    "generation": number;
    "stateJson": string;
}

export interface ManagedModel {
    "id": string;
    "name"?: string;
    "contextWindow": number;
    "maxTokens": number;
    "reasoning": boolean;
    "imageInput": boolean;
    "thinkingLevelMapJson"?: string;
    "compatJson"?: string;
}

export interface ManagedModelProvider {
    "id": string;
    "baseUrl"?: string;
    "api"?: string;
    "apiKey"?: string;
    "headers"?: { [_ in string]?: string } | null;
    "compatJson"?: string;
    "models": ManagedModel[] | null;
}

export interface ManagedSkill {
    "scope": SkillScope;
    "name": string;
    "description"?: string;
    "rootDirectory": string;
    "relativePath": string;
    "path": string;
    "directory": string;
    "kind": string;
    "enabled": boolean;
    "warnings"?: string[] | null;
    "content": string;
}

export interface ManagedSkillRequest {
    "scope": SkillScope;
    "workspacePath"?: string;
    "rootDirectory"?: string;
    "relativePath": string;
}

/**
 * ManagedSkillSnapshot reads the directories Pi natively scans. It deliberately
 * does not register a separate skill catalog.
 */
export interface ManagedSkillSnapshot {
    "globalDirectory": string;
    "globalDirectories": string[] | null;
    "projectDirectory"?: string;
    "projectEnabled": boolean;
    "projectNotice"?: string;
    "skills": ManagedSkillSummary[] | null;
}

export interface ManagedSkillSummary {
    "scope": SkillScope;
    "name": string;
    "description"?: string;
    "rootDirectory": string;
    "relativePath": string;
    "path": string;
    "directory": string;
    "kind": string;
    "enabled": boolean;
    "warnings"?: string[] | null;
}

export enum McpConfigScope {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    McpConfigScopeGlobal = "global",
    McpConfigScopeProject = "project",
};

/**
 * McpConfigSnapshot exposes Pi-owned writable layers plus the effective,
 * read-only configuration resolved by pi-mcp-adapter.
 */
export interface McpConfigSnapshot {
    "globalPath": string;
    "projectPath"?: string;
    "projectEnabled": boolean;
    "projectNotice"?: string;
    "adapterNotice"?: string;
    "servers": McpServerSummary[] | null;
    "effectiveServers": McpEffectiveServer[] | null;
    "sources": McpConfigSource[] | null;
}

export interface McpConfigSource {
    "id": string;
    "label": string;
    "path": string;
    "scope": McpConfigScope;
    "kind": string;
    "exists": boolean;
    "serverCount": number;
}

export interface McpEffectiveServer {
    "scope": McpConfigScope;
    "name": string;
    "transport": string;
    "endpoint"?: string;
    "disabled": boolean;
    "definition": string;
}

export interface McpEngineStatus {
    "source"?: string;
    "installed": boolean;
    "enabled": boolean;
    "shadowedPaths"?: string[] | null;
}

/**
 * McpEngineStatus describes the pi-mcp-adapter package that connects Pi to MCP
 * servers, plus shared config files the adapter also reads.
 */
export interface McpEngineStatusRequest {
    "workspacePath"?: string;
}

/**
 * McpImportCandidate is a server found in another host's configuration file
 * (Claude Code, Claude Desktop, Cursor, VS Code). Host carries a display name.
 */
export interface McpImportCandidate {
    "host": string;
    "path": string;
    "name": string;
    "definition": string;
}

export interface McpServer {
    "scope": McpConfigScope;
    "name": string;
    "transport": string;
    "endpoint"?: string;
    "disabled": boolean;
    "definition": string;
}

export interface McpServerRequest {
    "scope": McpConfigScope;
    "workspacePath"?: string;
    "name": string;
}

export interface McpServerSummary {
    "scope": McpConfigScope;
    "name": string;
    "transport": string;
    "endpoint"?: string;
    "disabled": boolean;
}

export interface McpServerTestResult {
    "transport": string;
    "protocolVersion"?: string;
    "serverName"?: string;
    "serverVersion"?: string;
    "capabilities": string[] | null;
    "tools": McpToolDetail[] | null;
    "resources": string[] | null;
    "prompts": string[] | null;
    "toolCount": number;
    "resourceCount": number;
    "promptCount": number;
    "durationMillis": number;
}

export interface McpToolDetail {
    "name": string;
    "description"?: string;
    "inputSchema"?: string;
}

export interface ModelConfigSnapshot {
    "path": string;
    "providers": ManagedModelProvider[] | null;
}

export interface ModelDiscoveryResult {
    "models": DiscoveredModel[] | null;
    "endpoint": string;
}

export interface ModelQuotaRequest {
    "baseUrl": string;
    "api": string;
    "apiKey"?: string;
    "headers"?: { [_ in string]?: string } | null;
}

export interface ModelQuotaResult {
    "ok": boolean;
    "latencyMs": number;
    "status"?: number;
    "endpoint"?: string;
    "summary"?: string;
    "detailsJson"?: string;
    "error"?: string;
}

export interface ModelRequest {
    "threadId": string;
    "provider": string;
    "modelId": string;
}

export interface ModelTestResult {
    "ok": boolean;
    "latencyMs": number;
    "status"?: number;
    "response"?: string;
    "error"?: string;
}

export interface OpenWorkspaceWithRequest {
    "workspaceId": string;
    "applicationId": string;
}

export interface OrphanSessionSummary {
    "id": string;
    "path": string;
    "anchorWorkspaceId": string;
    "targetId"?: string;
    "remoteRoot"?: string;
    "name"?: string;
    "title": string;
    "firstMessage": string;
    "createdAt": string;
    "modifiedAt": string;
    "messageCount": number;
}

export interface PiDeskBrowserExtensionStatus {
    "path": string;
    "installed": boolean;
    "updateAvailable": boolean;
}

export interface PiDeskComputerUseExtensionStatus {
    "path": string;
    "installed": boolean;
    "updateAvailable": boolean;
}

export interface PiDeskGoalExtensionStatus {
    "path": string;
    "installed": boolean;
    "updateAvailable": boolean;
}

export interface PiDeskSubagentsExtensionStatus {
    "path": string;
    "installed": boolean;
    "updateAvailable": boolean;
}

export interface PiDeskTodoExtensionStatus {
    "path": string;
    "installed": boolean;
    "updateAvailable": boolean;
    "legacyPath"?: string;
    "legacyInstalled": boolean;
    "legacyBackupPath"?: string;
}

export interface PiDeskTodoInstallResult {
    "todo": PiDeskTodoExtensionStatus;
    "replacedLegacy": boolean;
}

export enum PiExtensionOrigin {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PiExtensionOriginGlobal = "global",
    PiExtensionOriginSettings = "settings",
    PiExtensionOriginPackage = "package",
};

export interface PiExtensionSnapshot {
    "globalDirectory": string;
    "settingsPath": string;
    "extensions": PiExtensionSummary[] | null;
    "todo": PiDeskTodoExtensionStatus;
    "goal": PiDeskGoalExtensionStatus;
    "computerUse": PiDeskComputerUseExtensionStatus;
    "subagents": PiDeskSubagentsExtensionStatus;
    "browser": PiDeskBrowserExtensionStatus;
}

export interface PiExtensionSummary {
    "name": string;
    "source": string;
    "path"?: string;
    "origin": PiExtensionOrigin;
}

/**
 * PiMaintenanceAction is deliberately an enum rather than a shell command.
 * The desktop can maintain the Pi CLI without ever accepting executable text
 * from the frontend.
 */
export enum PiMaintenanceAction {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PiInstall = "install",
    PiUpdateSelf = "update-self",
};

export interface PiMaintenanceRequest {
    "action": PiMaintenanceAction;
}

export interface PiMaintenanceResult {
    "action": PiMaintenanceAction;
    "command"?: string;
    "output"?: string;
    "runtime": PiRuntimeStatus;
}

export interface PiPackageCommandResult {
    "output"?: string;
}

export interface PiPackageRequest {
    "source": string;
    "scope": PiPackageScope;
    "workspacePath"?: string;
}

export enum PiPackageScope {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PiPackageScopeGlobal = "global",
    PiPackageScopeProject = "project",
};

export interface PiPackageSnapshot {
    "globalSettingsPath": string;
    "projectSettingsPath"?: string;
    "projectEnabled": boolean;
    "projectNotice"?: string;
    "packages": PiPackageSummary[] | null;
}

export interface PiPackageSummary {
    "source": string;
    "scope": PiPackageScope;
    "enabled": boolean;
}

export interface PiRuntimeStatus {
    "state": RuntimeState;
    "command"?: string;
    "version"?: string;
    "message"?: string;
}

export interface PickWorkspaceRequest {
    "initialPath"?: string;
}

export interface PrepareRemoteRootRequest {
    "targetId": string;
    "name": string;
    "requestedRoot": string;
}

export interface PromptRequest {
    "threadId": string;
    "message": string;
    "streamingBehavior"?: string;
    "images"?: ImageContent[] | null;
}

export interface PromptTemplate {
    "scope": PromptTemplateScope;
    "name": string;
    "description"?: string;
    "argumentHint"?: string;
    "path": string;
    "content": string;
}

export interface PromptTemplateRequest {
    "scope": PromptTemplateScope;
    "workspacePath"?: string;
    "name": string;
}

export enum PromptTemplateScope {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PromptTemplateScopeGlobal = "global",
    PromptTemplateScopeProject = "project",
};

/**
 * PromptTemplateSnapshot maps directly to Pi's native prompt template directories.
 * Project templates are available only when the selected workspace is trusted.
 */
export interface PromptTemplateSnapshot {
    "globalDirectory": string;
    "projectDirectory"?: string;
    "projectEnabled": boolean;
    "projectNotice"?: string;
    "templates": PromptTemplateSummary[] | null;
}

export interface PromptTemplateSummary {
    "scope": PromptTemplateScope;
    "name": string;
    "description"?: string;
    "argumentHint"?: string;
    "path": string;
}

/**
 * ProviderEnvIssue names one provider whose API key is an environment reference ($VAR / ${VAR}) that
 * the running Pi Desk process cannot resolve, so Pi drops the provider and every model under it.
 * It exists because a .app launched by Finder never reads ~/.zshrc.
 */
export interface ProviderEnvIssue {
    "provider": string;
    "variable": string;
}

export interface QueueModeRequest {
    "threadId": string;
    "mode": string;
}

export interface RemoteAliasSummary {
    "name": string;
    "risky": boolean;
}

export interface RemoteRootCandidate {
    "token": string;
    "targetId": string;
    "hostAlias": string;
    "hostKeyAlgorithm": string;
    "hostKeySha256": string;
    "canonicalRoot": string;
    "device": string;
    "inode": string;
}

export interface RemoteTargetRequest {
    "targetId": string;
}

export interface RemoteTargetSummary {
    "id": string;
    "name": string;
    "hostAlias": string;
}

export interface RenameWorkspaceRequest {
    "id": string;
    "name": string;
}

export interface RepositoryFile {
    "path": string;
    "name": string;

    /**
     * Ignored: Git excludes this path (.gitignore / .git/info/exclude / core.excludesFile).
     * Directory: folder entry without listed children, because the scan was capped or the folder is
     * deliberately not expanded (node_modules). Only ignored entries ever carry it.
     */
    "ignored"?: boolean;
    "directory"?: boolean;
}

export interface RepositoryFileDiff {
    "path": string;
    "staged"?: string;
    "working"?: string;
    "content"?: string;
    "binary"?: boolean;
    "truncated"?: boolean;
}

export interface RepositoryFilePreview {
    "path": string;
    "absolutePath": string;
    "content"?: string;
    "mediaType"?: string;
    "dataUrl"?: string;
    "size": number;
    "binary"?: boolean;
    "truncated"?: boolean;
}

export interface RepositoryFileRequest {
    "workspaceId"?: string;
    "workspacePath"?: string;
    "path": string;
}

export interface RepositoryRequest {
    "workspaceId"?: string;
    "workspacePath"?: string;
}

export interface RepositorySaveFileRequest {
    "workspaceId"?: string;
    "workspacePath"?: string;
    "path": string;
    "outputPath": string;
}

export interface RepositorySnapshot {
    "files": RepositoryFile[] | null;
    "truncated"?: boolean;
    "git": GitStatus;
}

export interface RestoreOrphanSessionRequest {
    "path": string;
    "workspaceId": string;
}

export interface ResumeRemoteWorkspaceRequest {
    "workspaceId": string;
}

export interface RollbackSessionFileRequest {
    "workspaceId"?: string;
    "workspacePath"?: string;
    "sessionPath": string;
    "path": string;
}

export enum RuntimeState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RuntimeChecking = "checking",
    RuntimeReady = "ready",
    RuntimeMissing = "missing",
    RuntimeError = "error",
};

export interface ScheduledTaskState {
    "id": string;
    "name": string;
    "prompt": string;
    "workspaceId": string;
    "modelProvider"?: string;
    "modelId"?: string;
    "modelName"?: string;
    "thinkingLevel"?: string;
    "frequency": string;
    "time"?: string;
    "weekday"?: number;
    "runAt"?: string;
    "enabled": boolean;
    "nextRunAt"?: string;
    "lastRunAt"?: string;
    "lastThreadId"?: string;
    "lastStatus"?: string;
    "lastError"?: string;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * SelectableModel is the credential-free subset exposed outside model management.
 */
export interface SelectableModel {
    "id": string;
    "name"?: string;
    "provider": string;
    "contextWindow"?: number;
    "reasoning"?: boolean;
}

export interface SessionBranchEntry {
    "id": string;
    "parentId"?: string;
    "type": string;
    "timestamp"?: string;
    "role"?: string;
    "text"?: string;
    "label"?: string;
}

export interface SessionBranches {
    "entries": SessionBranchEntry[] | null;
    "leafId"?: string;
}

export interface SessionFileChange {
    "path": string;
    "editCalls": number;
    "writeCalls": number;
    "plan": string;
}

export interface SessionFileChanges {
    "files": SessionFileChange[] | null;
}

export interface SessionFileChangesRequest {
    "workspaceId"?: string;
    "workspacePath"?: string;
    "sessionPath": string;
}

export interface SessionForkRequest {
    "threadId": string;
    "entryId": string;
}

export interface SessionMessageRequest {
    "threadId": string;
    "path": string;
    "entryId": string;
    "text"?: string;
    "before"?: boolean;
}

export interface SessionModel {
    "provider": string;
    "id": string;
}

export interface SessionModelUsage {
    "provider": string;
    "model": string;
    "assistantMessages": number;
    "tokens": SessionTokenUsage;
    "cost": number;
}

export interface SessionNameRequest {
    "threadId": string;
    "name": string;
}

export interface SessionSnapshot {
    "messages": json$0.RawMessage[] | null;
    "model"?: SessionModel | null;
    "messageCount": number;
}

export interface SessionSnapshotRequest {
    "path": string;
}

export interface SessionSummary {
    "id": string;
    "path": string;
    "cwd": string;
    "anchorWorkspaceId"?: string;
    "name"?: string;
    "title": string;
    "firstMessage": string;
    "createdAt": string;
    "modifiedAt": string;
    "messageCount": number;
    "parentSessionPath"?: string;
}

export interface SessionTokenUsage {
    "input": number;
    "output": number;
    "cacheRead": number;
    "cacheWrite": number;
    "reasoning": number;
    "total": number;
}

export interface SessionUsageSummary {
    "sessions": number;
    "messages": number;
    "userMessages": number;
    "assistantMessages": number;
    "toolResults": number;
    "tokens": SessionTokenUsage;
    "cost": number;
    "models": SessionModelUsage[] | null;
}

export interface SetPiPackageEnabledRequest {
    "source": string;
    "scope": PiPackageScope;
    "workspacePath"?: string;
    "enabled": boolean;
}

export enum SkillScope {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SkillScopeGlobal = "global",
    SkillScopeProject = "project",
};

export interface StartSessionRequest {
    "threadId": string;
    "workspace": string;
    "workspaceId"?: string;
    "sessionPath"?: string;
    "sessionName"?: string;
    "trust": string;
    "noSession"?: boolean;
    "offline"?: boolean;
    "disableThemes"?: boolean;
    "disableSkills"?: boolean;
    "disablePlugins"?: boolean;
    "proxyUrl"?: string;
}

export interface StartTerminalRequest {
    "threadId": string;
    "workspaceId"?: string;
    "workspacePath"?: string;
    "columns": number;
    "rows": number;
}

export interface TerminalRequest {
    "threadId": string;
    "workspaceId"?: string;
}

export interface TerminalResizeRequest {
    "threadId": string;
    "columns": number;
    "rows": number;
}

export interface TerminalState {
    "threadId": string;
    "cwd"?: string;
    "shell"?: string;
    "running": boolean;
    "generation"?: number;
    "sequence": number;
    "outputB64"?: string;
}

export interface TerminalWriteRequest {
    "threadId": string;
    "data": string;
}

export interface TestMcpServerRequest {
    "workspacePath"?: string;
    "definition": string;
}

export interface TestModelConfigRequest {
    "baseUrl": string;
    "api": string;
    "apiKey"?: string;
    "headers"?: { [_ in string]?: string } | null;
    "modelId": string;
    "prompt": string;
}

export interface ThinkingRequest {
    "threadId": string;
    "level": string;
}

export interface ThreadRequest {
    "threadId": string;
}

export interface ToggleRequest {
    "threadId": string;
    "enabled": boolean;
}

export interface UpdateCheckResult {
    "status": string;
    "currentVersion": string;
    "latestVersion"?: string;
    "url"?: string;
    "notes"?: string;
    "checkedAt": string;
    "message": string;
}

export interface UpdateManagedSkillRequest {
    "scope": SkillScope;
    "workspacePath"?: string;
    "rootDirectory"?: string;
    "relativePath": string;
    "content": string;
}

export interface UpsertMcpServerRequest {
    "scope": McpConfigScope;
    "workspacePath"?: string;
    "originalName"?: string;
    "name": string;
    "definition": string;
}

export interface UpsertModelConfigRequest {
    "originalProviderId"?: string;
    "originalModelId"?: string;
    "providerId": string;
    "baseUrl"?: string;
    "api"?: string;
    "apiKey"?: string;
    "headers"?: { [_ in string]?: string } | null;
    "providerCompatJson"?: string;
    "modelId": string;
    "modelName"?: string;
    "contextWindow": number;
    "maxTokens": number;
    "reasoning": boolean;
    "imageInput": boolean;
    "thinkingLevelMapJson"?: string;
    "modelCompatJson"?: string;
}

export interface UpsertPromptTemplateRequest {
    "scope": PromptTemplateScope;
    "workspacePath"?: string;
    "originalName"?: string;
    "name": string;
    "content": string;
}

export interface WindowState {
    "x": number;
    "y": number;
    "width": number;
    "height": number;
    "maximized": boolean;
    "valid": boolean;
}

export interface WorkspaceApplication {
    "id": string;
    "name": string;
    "iconDataUrl": string;
}

export interface WorkspaceRequest {
    "id": string;
    "path"?: string;
}

export interface WorkspaceSummary {
    "id": string;
    "name": string;
    "path": string;
    "kind": string;
    "targetId"?: string;
    "remoteRoot"?: string;
    "trust": string;
    "addedAt": string;
    "lastOpenedAt": string;
}
